#!/bin/bash
#
# LemonBar Panel Script

datefmt="%d %b %H:%M"
alsactl=Master
battery=$(ls /sys/class/power_supply | grep BAT)

clock() {
    date "+${datefmt}"
}

battery() {
    BATC=/sys/class/power_supply/${battery}/capacity
    BATS=/sys/class/power_supply/${battery}status
    #test "`cat $BATS`" = "Charging" && echo -n '+' || echo -n '-'
    sed -n p $BATC
}

muted() {
	amixer get $alsactl | grep -o '\[off\]' >/dev/null && false || true
}

volume() {
    amixer get $alsactl | sed -n 'N;s/^.*\[\([0-9]\+%\).*$/\1/p'
}

cpuload() {
    LINE=`ps -eo pcpu |grep -vE '^\s*(0.0|%CPU)' |sed -n '1h;$!H;$g;s/\n/ +/gp'`
    bc <<< $LINE
}

memused() {
    read t f <<< `grep -E 'Mem(Total|Free)' /proc/meminfo |awk '{print $2}'`
    bc <<< "scale=2; 100 - $f / $t * 100" | cut -d. -f1
}

nowplaying() {
    cur=`mpc current`
    # this line allow to choose whether the output will scroll or not
    test "$1" = "scroll" && PARSER='skroll -n20 -d0.5 -r' || PARSER='cat'
    test -n "$cur" && $PARSER <<< $cur || echo "- stopped -"
}

focwin() {
	xtitle
}

while :; do
    buf=""
    buf="${buf} > $(focwin) <"
#    buf="${buf} CPU: $(cpuload)%% -"
#    buf="${buf} RAM: $(memused)%%"
	buf="${buf} %{c}|| $(clock) ||"
    buf="${buf} %{r}$(volume)%"
    buf="${buf} > $(nowplaying) <"

    echo $buf
    # use `nowplaying scroll` to get a scrolling output!
    sleep 1 # The HUD will be updated every second
done


